in_channels: &in_channels 3
seq_len: &seq_len 8
rm_global_scale: &rm_global_scale On
batch_size: 32
workers: 4
total_epochs: 150 
total_epochs_incremental_task: 100
step_per_epoch: &step_per_epoch On
step_per_batch: &step_per_batch Off
log_freq:
    train: 20
    val: null

model:
    name: 'dg_sta'
    in_channels: *in_channels
    n_heads: 8 # number of attention heads
    d_head: 32 # dimension of attention heads
    d_feat: 128 # feature dimension
    seq_len: *seq_len # sequence length
    n_joints: 42 # number of joints
    dropout: 0.2


transforms:
    train:
        stratified_sample:
            n_samples: *seq_len
               
    val: &transforms_inference
        stratified_sample:
            n_samples: *seq_len
            
    testval: *transforms_inference  
    testtrain: *transforms_inference 
    test: *transforms_inference  


loss:
    cross_entropy: 
        weight: 1.0
        ignore: null
        class_weight: null
        
    rdfcil_local_cross_entropy:
        weight: 1.0

    rkd:
        weight: 1.0
        in_dim1: 128
        in_dim2: 128
        proj_dim: 256

    hkd:
        weight: 1.0

optimizer:
    name: 'adam'
    lr: &lr 0.001
    lr_incremental_task: 0.001
    lr_finetune_incremental_task: 0.001 #0.0001
    betas: [0.9, 0.999]
    include_scheduler: False
    scheduler:
        name: 'linear'
        lr: *lr
        start_factor: 1
        end_factor: 0.001
        step_per_batch: *step_per_batch
        step_per_epoch: *step_per_epoch      
          

increm:
    load_pretrained_task0: True
    first_split_size: 59
    other_split_size: 1
    max_task: 25
    load_best_checkpoint_train: True  # Only for task_id == 1
    load_best_checkpoint_test: True # Only for task_id == 1
    freeze_feature_extractor: False
    freeze_classifier: False
    memory: 0
    learner:
        type: 'rdfcil'
        n_samples_per_class: 300
        power_iters: 1000         
        deep_inv_params: [0.1, 50, 0.001, 1, 1, 0, 1]  
        inversion_batch_size: 128
        inverted_acc_thred: 99
        start_finetuning_epochs : 80
        lambda_loss: [0.1,0.9,0.5]  #[1,0.1,0.1]  